version : "3.3"
services :
  frontend :
     container_name : "frontend-app"
     build : .
     ports :
         - "3000:3000"
     environment:
         - REACT_APP_SERVER_URL=http://3.94.53.86:8080/employees
